### ISSUE TITLE
root password in Debian template 2

### ISSUE THREAD

**Issue by sebaix** [freenas/vm-templates#14]
README says debian/debian but it doesn't have privileges...
I need to log into root to install sudo and other stuff.
Anyone can provide me with the root password in the Debian template?
Thank you for your help!

**Comment by jordanhubbard** [comment]
It's the same password, which I would hope many would guess, but updated README file anyway.

**Comment by sebaix** [comment]
I already tried that... doesn't work :(

**Comment by jordanhubbard** [comment]
... I just did it and it worked fine.  Are you SURE you are using the Debian template and didn't change it and forget?  I **just** created a brand new one and logged in as both debian and as root on the serial console (obviously ssh doesn't permit root login unless you enable that first, and that's by design in all ssh installs because it would be highly insecure otherwise).
<img width="829" alt="screen shot 2017-03-15 at 10 30 34 pm" src="https://cloud.githubusercontent.com/assets/5066252/23983077/0a2328b6-09cf-11e7-8910-a0b2e79966b6.png">

**Comment by sebaix** [comment]
My mistake. Apologies.
I always set this up... not this time :(
Thank you very much for your help!
Cheers.
