### ISSUE TITLE
pfsense ignore change of os diskspace

### ISSUE THREAD

**Issue by Joschka1** [freenas/vm-templates#8]
The pfsense template has as default 1GB for the os device, but this is to small for usage. If you change it on install to a higher value, it will still stay for 1 GB. 

Cheers 
Joschka! 

By the way a newer version of pfsense is available, version 2.3.2.

**Comment by jordanhubbard** [comment]
changing the size of a zvol alone will never work since the OS cannot see the change (nor do all guest OSes support live resize of their disk, though where they do, this is how to make them "see" then change - this will always be guest-OS specific as well, so there is nothing FreeNAS can do from its side alone).

**Comment by Joschka1** [comment]
but if i change it bevor installing, it will also have no influence or did I get this wrong?

**Comment by jordanhubbard** [comment]
You can't use a template if you're going to change the sizes - for that, you would install manually without a template (using manually created devices for CD, disk, NIC, and so on).
